const DELETE_CHAT = "DELETE_CHAT";
const ADD_CHAT = "ADD_CHAT";
const ADD_MESSAGE_IN_CHAT = "ADD_MESSAGE_IN_CHAT";
const ADD_ROBOT_IN_CHAT = "ADD_ROBOT_IN_CHAT";

export { DELETE_CHAT, ADD_CHAT, ADD_MESSAGE_IN_CHAT, ADD_ROBOT_IN_CHAT };
