const ADD_PHOTO_PEXELS = "ADD_PHOTO_PEXELS";
const DELETE_PHOTO_PEXELS = "DELETE_PHOTO_PEXELS";
const SET_PHOTO_PEXELS = "GET_PHOTO_PEXELS";
const ERROR_PEXELS = "ERROR_PEXELS";

export {
  ADD_PHOTO_PEXELS,
  DELETE_PHOTO_PEXELS,
  SET_PHOTO_PEXELS,
  ERROR_PEXELS,
};
