// export const DELETE_PROFILE_ITEM = "DELETE_PROFILE_ITEM";
// export const ADD_PROFILE_ITEM = "ADD_PROFILE_ITEM";

const DELETE_PROFILE_ITEM = "DELETE_PROFILE_ITEM";
const ADD_PROFILE_ITEM = "ADD_PROFILE_ITEM";
export { ADD_PROFILE_ITEM, DELETE_PROFILE_ITEM };
